# Generated by Django 4.2.3 on 2023-07-05 09:14

import django.db.models.deletion
from django.db import migrations, models

import messages_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Номер телефона в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', max_length=11, unique=True, validators=[messages_app.models.validate_phone_number], verbose_name='Номер телефона')),
                ('tag', models.CharField(blank=True, max_length=30, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(help_text='Начало отправки сообщений пользователям.', verbose_name='Начать рассылку')),
                ('end_at', models.DateTimeField(help_text='Окончание отправки сообщений пользователям.', verbose_name='Закончить рассылку')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massages', to='messages_app.sending', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
