# Generated by Django 4.2.3 on 2023-07-05 12:17

import django.db.models.deletion
from django.db import migrations, models

import messages_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOperatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_operator_code', models.CharField(max_length=3, validators=[messages_app.models.validate_mobile_operator_code], verbose_name='Код мобильного оператора')),
            ],
            options={
                'verbose_name': 'Код мобильного оператора',
                'verbose_name_plural': 'Коды мобильных операторов',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_operator_code',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='messages_app.mobileoperatorcode', verbose_name='Код мобильного оператора'),
            preserve_default=False,
        ),
    ]
