# Generated by Django 4.2.3 on 2023-07-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_mobileoperatorcode_client_mobile_operator_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile_operator_code',
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='messages_app.tag', verbose_name='Тег'),
        ),
    ]
