# Generated by Django 4.2.3 on 2023-07-05 12:53

from django.db import migrations, models

import messages_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_tag_remove_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', max_length=11, validators=[messages_app.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('phone_number', 'tag')},
        ),
    ]
