# Generated by Django 4.2.3 on 2023-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='client_mobile_operator_codes',
            field=models.ManyToManyField(help_text='Коды мобильных операторов клиентов, которым будет отправлено сообщение.', related_name='sending', to='messages_app.mobileoperatorcode', verbose_name='Коды мобильных операторов клиентов'),
        ),
        migrations.AddField(
            model_name='sending',
            name='client_tags',
            field=models.ManyToManyField(help_text='Теги клиентов, которым будет отправлено сообщение.', related_name='sending', to='messages_app.tag', verbose_name='Теги клиентов'),
        ),
    ]
