# Generated by Django 4.2.3 on 2023-07-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0005_sending_client_mobile_operator_codes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileoperatorcode',
            old_name='mobile_operator_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_operator_code',
            field=models.ForeignKey(blank=True, help_text='Заполняется автоматически, после сохранения данных', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='messages_app.mobileoperatorcode', verbose_name='Код мобильного оператора'),
        ),
    ]
