version: "3"

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-123}
      - POSTGRES_USER=${POSTGRES_USER-root}
      - POSTGRES_NAME=${POSTGRES_NAME-db_auth}
    image: postgres:14.8

  django:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static:/code/static
    environment:
      SECRET_KEY: ${SECRET_KEY-change_me}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS-0.0.0.0}
      DEBUG: ${DEBUG-True}
      DATABASE_URL: ${DATABASE_URL-postgres://root:123@db_auth:/postgres}
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db_auth


  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/code
      - static:/code/static
    links:
      - redis
    depends_on:
      - redis


volumes:
  static:

