# Generated by Django 4.2.3 on 2023-07-10 00:51

from django.db import migrations, models
import django.db.models.deletion
import mailings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MobileOperatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, validators=[mailings.models.validate_mobile_operator_code], verbose_name='Код мобильного оператора')),
            ],
            options={
                'verbose_name': 'Код мобильного оператора',
                'verbose_name_plural': 'Коды мобильных операторов',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(help_text='Начало отправки сообщений пользователям.', verbose_name='Начать рассылку')),
                ('end_at', models.DateTimeField(help_text='Окончание отправки сообщений пользователям.', verbose_name='Закончить рассылку')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'В процессе'), ('completed', 'Завершена')], help_text='Присваивается автоматически.', max_length=20, verbose_name='Статус')),
                ('client_mobile_operator_codes', models.ManyToManyField(help_text='Коды мобильных операторов клиентов, которым будет отправлено сообщение.', related_name='mailings', to='mailings.mobileoperatorcode', verbose_name='Коды мобильных операторов клиентов')),
                ('client_tags', models.ManyToManyField(help_text='Теги клиентов, которым будет отправлено сообщение.', related_name='mailings', to='mailings.tag', verbose_name='Теги клиентов')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailings.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Номер телефона в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', max_length=11, validators=[mailings.models.validate_phone_number], verbose_name='Номер телефона')),
                ('mobile_operator_code', models.ForeignKey(blank=True, help_text='Заполняется автоматически, после сохранения данных', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='mailings.mobileoperatorcode', verbose_name='Код мобильного оператора')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='mailings.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'unique_together': {('phone_number', 'tag')},
            },
        ),
    ]
