# Generated by Django 4.2.3 on 2023-07-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает рассылки'), ('active', 'Активная рассылка'), ('completed', 'Рассылка завершена')], default='Ожидает рассылки', max_length=20, verbose_name='Статус'),
        ),
    ]
