# Generated by Django 4.2.3 on 2023-07-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mailing_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID рассылки'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено'),
        ),
    ]
