# Generated by Django 4.2.3 on 2023-07-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает рассылки'), ('active', 'Активная рассылка'), ('completed', 'Рассылка завершена')], help_text='Присваивается автоматически.', max_length=20, verbose_name='Статус'),
        ),
    ]
