# Generated by Django 4.2.3 on 2023-07-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_message_mailing_id_message_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailing_id',
        ),
    ]
